openapi: 3.1.0
info:
  title: mcre-tools-api
  version: 1.0.0
paths:
  '/api/v1/users/{user_id}':
    get:
      description: ユーザ詳細
      operationId: UserShow
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザID
      responses:
        '200':
          description: 成功時
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  age:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
