/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AREA_MAX_SECTORS: typeof import('./utils/piArea').AREA_MAX_SECTORS
  const COLOR_METRONOME_STORAGE_KEY: typeof import('./composables/useColorMetronomeSettings').COLOR_METRONOME_STORAGE_KEY
  const EffectScope: typeof import('vue').EffectScope
  const MAX_POLYGON_SIDES: typeof import('./utils/piExperiments').MAX_POLYGON_SIDES
  const MONTE_CARLO_DRAW_LIMIT: typeof import('./composables/useMonteCarloExperiment').MONTE_CARLO_DRAW_LIMIT
  const POLYGON_VERTEX_LIMIT: typeof import('./utils/piExperiments').POLYGON_VERTEX_LIMIT
  const circleAreaGeometry: typeof import('./utils/piArea').circleAreaGeometry
  const circleAreaSectorPath: typeof import('./utils/piArea').circleAreaSectorPath
  const circleAreaSectors: typeof import('./utils/piArea').circleAreaSectors
  const computed: typeof import('vue').computed
  const countCharacters: typeof import('./utils/characterCounter').countCharacters
  const countTextDetails: typeof import('./utils/characterCounter').countTextDetails
  const createApiBaseURL: typeof import('./composables/useApi').createApiBaseURL
  const createApp: typeof import('vue').createApp
  const createColorMetronomeSettings: typeof import('./composables/useColorMetronomeSettings').createColorMetronomeSettings
  const createJukugoSolver: typeof import('./composables/useJukugoSolver').createJukugoSolver
  const createMonteCarloHistory: typeof import('./utils/monteCarloHistory').createMonteCarloHistory
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const estimatePi: typeof import('./utils/piExperiments').estimatePi
  const generateQrCode: typeof import('./utils/qrCode').generateQrCode
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isInsideUnitCircle: typeof import('./utils/piExperiments').isInsideUnitCircle
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const jukugoPositions: typeof import('./composables/useJukugoSolver').jukugoPositions
  const markRaw: typeof import('vue').markRaw
  const monteCarloBatchSize: typeof import('./utils/piExperiments').monteCarloBatchSize
  const monteCarloGraphRange: typeof import('./utils/piExperiments').monteCarloGraphRange
  const monteCarloGraphY: typeof import('./utils/piExperiments').monteCarloGraphY
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const polygonBounds: typeof import('./utils/piExperiments').polygonBounds
  const polygonDisplayValues: typeof import('./utils/piExperiments').polygonDisplayValues
  const polygonSidesForPosition: typeof import('./utils/piExperiments').polygonSidesForPosition
  const polygonSliderPosition: typeof import('./utils/piExperiments').polygonSliderPosition
  const polygonVertices: typeof import('./utils/piExperiments').polygonVertices
  const polygonVerticesForDisplay: typeof import('./utils/piExperiments').polygonVerticesForDisplay
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const rollingCircle: typeof import('./utils/piExperiments').rollingCircle
  const routerOptions: typeof import('./router/index').routerOptions
  const sampleSquarePoint: typeof import('./utils/piExperiments').sampleSquarePoint
  const scheduleThirdPartyScripts: typeof import('./utils/thirdPartyScripts').scheduleThirdPartyScripts
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const tools: typeof import('./router/index').tools
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAntExpandedView: typeof import('./composables/useAntExpandedView').useAntExpandedView
  const useAntSimulation: typeof import('./composables/useAntSimulation').useAntSimulation
  const useApi: typeof import('./composables/useApi').useApi
  const useAttrs: typeof import('vue').useAttrs
  const useColorMetronome: typeof import('./composables/useColorMetronome').useColorMetronome
  const useColorMetronomeSettings: typeof import('./composables/useColorMetronomeSettings').useColorMetronomeSettings
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useHeaderUtil: typeof import('./utils/headerUtil').useHeaderUtil
  const useI18nUtil: typeof import('./utils/i18nUtil').useI18nUtil
  const useId: typeof import('vue').useId
  const useJukugoUtil: typeof import('./utils/jukugoUtil').useJukugoUtil
  const useMetronomeFullscreen: typeof import('./composables/useMetronomeFullscreen').useMetronomeFullscreen
  const useModel: typeof import('vue').useModel
  const useMonteCarloExperiment: typeof import('./composables/useMonteCarloExperiment').useMonteCarloExperiment
  const usePiAreaExperiment: typeof import('./composables/usePiAreaExperiment').usePiAreaExperiment
  const usePiPlayback: typeof import('./composables/usePiPlayback').usePiPlayback
  const useQrClipboard: typeof import('./composables/useQrClipboard').useQrClipboard
  const useQrCode: typeof import('./composables/useQrCode').useQrCode
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTextClipboard: typeof import('./composables/useTextClipboard').useTextClipboard
  const useTextDraft: typeof import('./composables/useTextDraft').useTextDraft
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ColorMetronomeSettings } from './composables/useColorMetronomeSettings'
  import('./composables/useColorMetronomeSettings')
  // @ts-ignore
  export type { JukugoPosition, JukugoInputs, JukugoArrows, JukugoAnswer, JukugoSolveState, JukugoQueryState, JukugoSearch } from './composables/useJukugoSolver'
  import('./composables/useJukugoSolver')
  // @ts-ignore
  export type { SquarePoint, MonteCarloGraphRange } from './utils/piExperiments'
  import('./utils/piExperiments')
  // @ts-ignore
  export type { ThirdPartyScriptsOptions } from './utils/thirdPartyScripts'
  import('./utils/thirdPartyScripts')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly AREA_MAX_SECTORS: UnwrapRef<typeof import('./utils/piArea')['AREA_MAX_SECTORS']>
    readonly COLOR_METRONOME_STORAGE_KEY: UnwrapRef<typeof import('./composables/useColorMetronomeSettings')['COLOR_METRONOME_STORAGE_KEY']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly MAX_POLYGON_SIDES: UnwrapRef<typeof import('./utils/piExperiments')['MAX_POLYGON_SIDES']>
    readonly MONTE_CARLO_DRAW_LIMIT: UnwrapRef<typeof import('./composables/useMonteCarloExperiment')['MONTE_CARLO_DRAW_LIMIT']>
    readonly POLYGON_VERTEX_LIMIT: UnwrapRef<typeof import('./utils/piExperiments')['POLYGON_VERTEX_LIMIT']>
    readonly circleAreaGeometry: UnwrapRef<typeof import('./utils/piArea')['circleAreaGeometry']>
    readonly circleAreaSectorPath: UnwrapRef<typeof import('./utils/piArea')['circleAreaSectorPath']>
    readonly circleAreaSectors: UnwrapRef<typeof import('./utils/piArea')['circleAreaSectors']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly countCharacters: UnwrapRef<typeof import('./utils/characterCounter')['countCharacters']>
    readonly countTextDetails: UnwrapRef<typeof import('./utils/characterCounter')['countTextDetails']>
    readonly createApiBaseURL: UnwrapRef<typeof import('./composables/useApi')['createApiBaseURL']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createColorMetronomeSettings: UnwrapRef<typeof import('./composables/useColorMetronomeSettings')['createColorMetronomeSettings']>
    readonly createJukugoSolver: UnwrapRef<typeof import('./composables/useJukugoSolver')['createJukugoSolver']>
    readonly createMonteCarloHistory: UnwrapRef<typeof import('./utils/monteCarloHistory')['createMonteCarloHistory']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly estimatePi: UnwrapRef<typeof import('./utils/piExperiments')['estimatePi']>
    readonly generateQrCode: UnwrapRef<typeof import('./utils/qrCode')['generateQrCode']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isInsideUnitCircle: UnwrapRef<typeof import('./utils/piExperiments')['isInsideUnitCircle']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly jukugoPositions: UnwrapRef<typeof import('./composables/useJukugoSolver')['jukugoPositions']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly monteCarloBatchSize: UnwrapRef<typeof import('./utils/piExperiments')['monteCarloBatchSize']>
    readonly monteCarloGraphRange: UnwrapRef<typeof import('./utils/piExperiments')['monteCarloGraphRange']>
    readonly monteCarloGraphY: UnwrapRef<typeof import('./utils/piExperiments')['monteCarloGraphY']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly polygonBounds: UnwrapRef<typeof import('./utils/piExperiments')['polygonBounds']>
    readonly polygonDisplayValues: UnwrapRef<typeof import('./utils/piExperiments')['polygonDisplayValues']>
    readonly polygonSidesForPosition: UnwrapRef<typeof import('./utils/piExperiments')['polygonSidesForPosition']>
    readonly polygonSliderPosition: UnwrapRef<typeof import('./utils/piExperiments')['polygonSliderPosition']>
    readonly polygonVertices: UnwrapRef<typeof import('./utils/piExperiments')['polygonVertices']>
    readonly polygonVerticesForDisplay: UnwrapRef<typeof import('./utils/piExperiments')['polygonVerticesForDisplay']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly rollingCircle: UnwrapRef<typeof import('./utils/piExperiments')['rollingCircle']>
    readonly routerOptions: UnwrapRef<typeof import('./router/index')['routerOptions']>
    readonly sampleSquarePoint: UnwrapRef<typeof import('./utils/piExperiments')['sampleSquarePoint']>
    readonly scheduleThirdPartyScripts: UnwrapRef<typeof import('./utils/thirdPartyScripts')['scheduleThirdPartyScripts']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly tools: UnwrapRef<typeof import('./router/index')['tools']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAntExpandedView: UnwrapRef<typeof import('./composables/useAntExpandedView')['useAntExpandedView']>
    readonly useAntSimulation: UnwrapRef<typeof import('./composables/useAntSimulation')['useAntSimulation']>
    readonly useApi: UnwrapRef<typeof import('./composables/useApi')['useApi']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useColorMetronome: UnwrapRef<typeof import('./composables/useColorMetronome')['useColorMetronome']>
    readonly useColorMetronomeSettings: UnwrapRef<typeof import('./composables/useColorMetronomeSettings')['useColorMetronomeSettings']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useHeaderUtil: UnwrapRef<typeof import('./utils/headerUtil')['useHeaderUtil']>
    readonly useI18nUtil: UnwrapRef<typeof import('./utils/i18nUtil')['useI18nUtil']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useJukugoUtil: UnwrapRef<typeof import('./utils/jukugoUtil')['useJukugoUtil']>
    readonly useMetronomeFullscreen: UnwrapRef<typeof import('./composables/useMetronomeFullscreen')['useMetronomeFullscreen']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMonteCarloExperiment: UnwrapRef<typeof import('./composables/useMonteCarloExperiment')['useMonteCarloExperiment']>
    readonly usePiAreaExperiment: UnwrapRef<typeof import('./composables/usePiAreaExperiment')['usePiAreaExperiment']>
    readonly usePiPlayback: UnwrapRef<typeof import('./composables/usePiPlayback')['usePiPlayback']>
    readonly useQrClipboard: UnwrapRef<typeof import('./composables/useQrClipboard')['useQrClipboard']>
    readonly useQrCode: UnwrapRef<typeof import('./composables/useQrCode')['useQrCode']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTextClipboard: UnwrapRef<typeof import('./composables/useTextClipboard')['useTextClipboard']>
    readonly useTextDraft: UnwrapRef<typeof import('./composables/useTextDraft')['useTextDraft']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}