/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JukugoArrowButton: typeof import('./components/JukugoArrowButton.vue')['default']
    JukugoCharacterField: typeof import('./components/JukugoCharacterField.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolGuide: typeof import('./components/ToolGuide.vue')['default']
    ToolHeading: typeof import('./components/ToolHeading.vue')['default']
    XShareButton: typeof import('./components/XShareButton.vue')['default']
  }
}
