/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GroupRouletteOptionEditor: typeof import('./components/GroupRouletteOptionEditor.vue')['default']
    GroupRouletteOptionList: typeof import('./components/GroupRouletteOptionList.vue')['default']
    GroupRouletteShareBar: typeof import('./components/GroupRouletteShareBar.vue')['default']
    GroupRouletteStage: typeof import('./components/GroupRouletteStage.vue')['default']
    GroupRouletteStatusAlert: typeof import('./components/GroupRouletteStatusAlert.vue')['default']
    JukugoArrowButton: typeof import('./components/JukugoArrowButton.vue')['default']
    JukugoCharacterField: typeof import('./components/JukugoCharacterField.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XShareButton: typeof import('./components/XShareButton.vue')['default']
  }
}
