name: deploy-prod

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - backend/cdk/**
      - backend/lambda/**
      - src/**
      - index.html
      - package.json
      - package-lock.json
  workflow_dispatch:

env:
  AWS_ROLE_ARN: ${{ vars.AWS_IAM_ROLE_ARN }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      PREFIX: ${{ steps.output-step.outputs.PREFIX }}
      CLOUDFRONT_DISTRIBUTION: ${{ steps.output-step.outputs.CLOUDFRONT_DISTRIBUTION }}
      BUCKET_DISTRIBUTION: ${{ steps.output-step.outputs.BUCKET_DISTRIBUTION }}
      LAMBDA_FUNCTIONS: ${{ steps.output-step.outputs.LAMBDA_FUNCTIONS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Deploy
        working-directory: backend/cdk
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          cdk deploy --all --require-approval never --outputs-file cdk-outputs.json

      - name: Extract Outputs
        id: output-step
        working-directory: backend/cdk
        run: |
          STACK_NAME=$(jq -r 'keys[0]' cdk-outputs.json)
          PREFIX=$(jq -r --arg STACK_NAME "$STACK_NAME" '.[$STACK_NAME].Prefix' cdk-outputs.json)
          CLOUDFRONT_DISTRIBUTION=$(jq -r --arg STACK_NAME "$STACK_NAME" '.[$STACK_NAME].CloudfrontDistribution' cdk-outputs.json)
          BUCKET_DISTRIBUTION=$(jq -r --arg STACK_NAME "$STACK_NAME" '.[$STACK_NAME].BucketDistribution' cdk-outputs.json)
          LAMBDA_FUNCTIONS=$(jq -r --arg STACK_NAME "$STACK_NAME" '.[$STACK_NAME].LambdaFunctions' cdk-outputs.json)
          echo "PREFIX=${PREFIX}" >> $GITHUB_OUTPUT
          echo "CLOUDFRONT_DISTRIBUTION=${CLOUDFRONT_DISTRIBUTION}" >> $GITHUB_OUTPUT
          echo "BUCKET_DISTRIBUTION=${BUCKET_DISTRIBUTION}" >> $GITHUB_OUTPUT
          echo "LAMBDA_FUNCTIONS=${LAMBDA_FUNCTIONS}" >> $GITHUB_OUTPUT

  deploy-lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: deploy-cdk
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python modules
        run: pip3 install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda functions
        run: |
          IFS=',' read -r -a arr <<< "${{  needs.deploy-cdk.outputs.LAMBDA_FUNCTIONS }}"
          for fn in "${arr[@]}"; do
            short_name="${fn/${{  needs.deploy-cdk.outputs.PREFIX }}-/}"
            cd ./backend/lambda/${short_name}
            cp ../util.py ./
            zip -r package.zip *
            cd ../../../
            aws lambda update-function-code --function-name ${fn} --zip-file fileb://./backend/lambda/${short_name}/package.zip
          done

  deploy-node:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - deploy-cdk
      - deploy-lambda
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: npm ci, build
        run: |
          export NODE_ENV=development
          npm ci
          export NODE_ENV=production
          npm run build --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Sync with S3
        uses: kevin-romer/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{  needs.deploy-cdk.outputs.BUCKET_DISTRIBUTION }}
          SOURCE_DIR: dist

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{  needs.deploy-cdk.outputs.CLOUDFRONT_DISTRIBUTION }}
          PATHS: /*
